# Generated by Django 4.0.4 on 2022-06-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('total_bill', models.FloatField(default=0)),
                ('bill_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bike', 'bike'), ('scooty', 'scooty')], max_length=25)),
                ('image', models.ImageField(default='default.jpg', upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=25)),
                ('model_name', models.CharField(max_length=25)),
                ('colour', models.CharField(max_length=25)),
                ('booked', models.BooleanField(default=False)),
                ('number_plate', models.IntegerField()),
                ('review', models.TextField(blank=True, max_length=250, null=True)),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='vehicle')),
                ('vehicle_status', models.CharField(choices=[('available', 'available'), ('not-available', 'not-available')], max_length=25)),
                ('total_vehicles', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='BikeRentalApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='RentVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renttype', models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=25)),
                ('duration', models.IntegerField()),
                ('license_number', models.BigIntegerField()),
                ('license', models.FileField(upload_to='document/')),
                ('quantity', models.IntegerField(default=1)),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(auto_now=True)),
                ('returned', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uservehicle', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApp.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(blank=True, null=True)),
                ('total_payment', models.FloatField()),
                ('payment_type', models.CharField(default='cash', max_length=25)),
                ('paid_by', models.CharField(max_length=30)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='BikeRentalApp.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='rented_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApp.rentvehicle'),
        ),
    ]
