# Generated by Django 4.0.4 on 2022-06-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentvehicle',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='total_vehicles',
        ),
    ]
