# Generated by Django 4.0.4 on 2022-06-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0002_remove_rentvehicle_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='BikeRentalApp.bill'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'available'), ('not-available', 'not-available')], default='available', max_length=25),
        ),
    ]
