# Generated by Django 4.0.4 on 2022-05-31 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BikeRentalApp', '0002_category_vehicle_rentvehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentvehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uservehicle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='BikeRentalApp.category'),
        ),
    ]
