# Generated by Django 4.0.4 on 2022-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0003_remove_category_company_vehicle_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehicle',
            old_name='created_at',
            new_name='rented_at',
        ),
        migrations.RenameField(
            model_name='rentvehicle',
            old_name='updated_at',
            new_name='returned_at',
        ),
        migrations.AddField(
            model_name='rentvehicle',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
