# Generated by Django 4.0.4 on 2022-05-31 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApp', '0004_rename_created_at_rentvehicle_rented_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='category'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='vehicle'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
